### ISSUE TITLE
"YAM GetVar codeset_default Global Fehl"

### ISSUE THREAD

**Issue by halle-saale** [jens-maus/libcodesets#1]
Das gibt SnoopDos aus, nachdem YAM 2.10dev gestartet wurde. Davor wurde folgendes geladen:
- picture.datatype wird geladen, OK
- locale.library Ver 38 wird geladen, OK
- codesets.library Ver 6 wird geladen, OK

Anschließend erscheint obige Fehlermeldung über 2000 Mal.
Wonach sucht YAM da?

**Comment by tboeckel** [comment]
Wonach YAM bzw die codesets.library sucht steht da doch: nach der globalen Variablen ENV:codeset_default.

Wenn codesets.library irgendwelche Konvertierungen von einem Codeset in einen anderen vornehmen muss und dabei einer von beiden nicht exakt spezifiziert ist, wird auf mehrere Arten versucht ein Standard-Codeset für das jeweilige System zu ermitteln. Den kann man u.a. über diese Variable erzwingen, falls die interne Logik den falschen ermitteln sollte oder man das System (aus welchem Grund auch immer) auf einen anderen Codeset zwingen will.

Normalerweise wird die Variable also gar nicht benötigt, und deswegen kann sich natürlich auch nicht gefunden werden. Aber selbst mit dieser Variable würde der Overhead nicht weniger, weil die Suche nach einem geeigneten Codeset auch weiterhin passiert, lediglich die Suche nach der Variablen würde nicht mehr fehlschlagen.

**Comment by halle-saale** [comment]
Vielen Dank für die Antwort und die Erläuterungen.
Allerdings sehe ich da nicht so recht einen Lösungsvorschlag. Bitte nicht falsch verstehen, ich habe von Programmierung nicht die leisteste Ahnung. Fakt ist doch aber, dass durch diesen massiven, wiederholten Aufruf YAM für mindestens 10 Sekunden lahmgelegt wird (auf meinem System 1200). 
Das als gegeben hinzunehmen erscheint mir nicht als geeigente Lösung.
Für mich als Laien wäre es logisch, dass entweder
a) dieser Aufruf durch YAM gar nicht erst gestartet wird (wenn diese Variable, wie du sagst, gar nicht nötig ist) oder
b) der Aufruf nach dem ersten Versuch abgebrochen wird, sollte YAM diese codeset_default Datei in ENV nicht finden (was ja in jedem Fall vernünftig wäre!). 

Sollte ich als Anweder da irgendeine Steuerungsmöglichkeit haben, dann versuche icg es gerne. Ansonsten wöre es doch empfehleneswert, diese Sache in YAM und/oder der codeset.library zu ändern.

**Comment by tboeckel** [comment]
> Bitte nicht falsch verstehen, ich habe von Programmierung nicht die leisteste Ahnung.

Tut mir leid, wenn ich das so direkt sagen muss, aber wenn du vom Programmieren keine Ahnung hast, dann sollest du den Programmierern nicht erklären was sie falsch machen bzw wie es besser zu machen wäre.

YAM speichert alle für den Postfach-Index relevanten Texte (zB Empfänger, Sender, Betreff) als UTF8 ab. D.h. alle Text müssen entsprechend konvertiert werden. Umgekehrt beim Laden des Index werden alle UTF8-Strings wieder in den lokalen System-Codeset konvertiert. Und genau dies verursacht deine 2000 Funktionsaufrufe, von denen jeder die Präsenz der Variablen prüft, falls das aufrufende Programm keinen gültigen Ziel-Codeset vorgibt.

Dieses Hin- und Herkonvertieren ist nötig, damit der Index unabhängig von deinen momenanten Systemeinstellungen gespeichert wird. Früher wurde der Index mit dem System-Codeset gespeichert und es gab regelmäßig Beschwerden über falsche Zeichen, sobald irgendwas am System umgestellt wurde. Deswegen der Wechsel zu UTF8.

> a) dieser Aufruf durch YAM gar nicht erst gestartet wird (wenn diese Variable, wie du sagst, gar nicht nötig ist) oder
> b) der Aufruf nach dem ersten Versuch abgebrochen wird, sollte YAM diese codeset_default Datei in ENV nicht finden (was ja in jedem Fall vernünftig wäre!).

YAM hat und soll auch keine Ahnung von den Interna der codesets.library haben. So etwas nennt man "black box". Man weiss einfach nur, dass eine Funktion genau das tut, was sie soll, aber wie sie es tut interessiert einen nicht. YAM kann also keinen Aufruf vermeiden oder irgendetwas abbrechen.

> Sollte ich als Anweder da irgendeine Steuerungsmöglichkeit haben, dann versuche icg es gerne.

Prüf die Einstellungen für den System-Codeset auf der "Erste Schritte" Seite. Eigentlich sollte YAM da bereits selbst etwas sinnvolles eingetragen haben.

**Comment by halle-saale** [comment]
Und eben weil ich nur ein einfacher Anwender bin, versuche ich die Entwickler und ggf. auch andere Nutzer zu unterstützen, in dem ich auf Dinge aufmerksam mache, sie melde, die offensichtlich nicht so funktionieren wie sie sollten. Deshalb habe ich oben berichtet. Dafür möchte ich kein Dankeschön, muss mich aber auch nicht entschuldigen.
Und ich muss auch nicht verstehen, warum 2000 Mal eine Variable versucht wird aufzurufen - ich sehe nur, dass es massive Verschwendung von Ladezeit ist.
Und als einfacher Anwender bin dann ebenso darauf angewiesen, bestenfalls vom Entwickler Lösungsvorschläge zu bekommen. Da ich sie nicht erhalten hatte, habe ich meine Gedankengänge dargelegt. Punkt.

Ich habe nun selber versucht, verschiedene Charsets in YAM einzustellen: Einheitlich UTF-8 oder, wie ursprünglich, ISO-8859-1 + Euro. Die Aufrufe kommen trotzdem. Und bei UTF-8 werden Umlaute nicht dargestellt. 
Trotzdem, Danke für die Antworten.

**Comment by tboeckel** [comment]
> Und eben weil ich nur ein einfacher Anwender bin, versuche ich die Entwickler und ggf. auch andere Nutzer zu unterstützen, in dem ich auf Dinge aufmerksam mache, sie melde, die offensichtlich nicht so funktionieren wie sie sollten.

Auf solche Hinweise sind wir als Entwickler auch angewiesen und prinzipiell auch sehr froh. Man schaut sich die Codestellen dann ein weiteres Mal an, und stellt sich selbst die Frage, ob der Code so in Ordnung ist und denkt über mögliche Verbesserungen nach. Es reicht aber der Hinweis und die Frage, ob das beobachtete Verhalten so gewollt ist. Eine Belehrung, was und wie man alles schöner und besser machen könnte, passt aber eben nicht zur Aussage "ich habe nicht die leiseste Ahnung".

> ich sehe nur, dass es massive Verschwendung von Ladezeit ist.

Und genau diese Interpretation ist falsch, weil dir das nötige Hintergrundwissen für eine korrekte Einschätzung der Lage. Es ist keine Verschwendung. Es ist nötig und unumgänglich. Ich erwarte von keinem Anwender, dass er dieses Hintergrundwissen hat. Sogar ich musste mir die Stelle im Quellcode nochmals genau ansehen, damit ich dir genau erklären konnte warum da so viele Konvertierungen passieren.

Zusätzlich zum Laden der Postfach-Indices muss YAM unter AmigaOS3, MorphOS und AROS auch noch den Sprachkatalog von UTF8 in den System-Codeset konvertieren, was ebenfalls zZ 2060 weitere Aufrufe erzeugt. Auch das lässt sich nicht vermeiden. AmigaOS4 hat hier den kleinen Vorteil, dass die locale.library hier die Konvertierung intern und ohne codesets.library vornimmt. Die Konvertierung passiert aber auch hier, nur auf anderem Wege.

> Und bei UTF-8 werden Umlaute nicht dargestellt.

Das ist kein Wunder, weil in dem Fall gar keine Konvertierung statt findet und die Systemfunktionen für Textausgabe einen UTF8 kodierten String vorgesetzt bekommen, den sie natürlich nicht wie gewünscht korrekt darstellen können, weil AmigaOS selbst kein UTF8 beherscht. Daher ist UTF8 für den System-Codeset auch eine sehr schlechte Wahl. Beim Schreiben von Mails ist es jedoch eine recht gute Wahl, weil damit Umlaute auf jedem anderen Empfänger-System garantiert korrekt dargestellt werden. Das werden sie bei ISO8859-x zwar auch, jedoch lässt UTF8 dem Empfänger keinen Interpretationsspielraum, den es bei ISO8859-x eventuell geben könnte.

> Die Aufrufe kommen trotzdem.

Genau das ist es, was ich dir bereits erklärt habe. Der Index und die Sprachkataloge sind als UTF8 gespeichert. Weil dein System kein UTF8 kennt, müssen alle Texte von UTF8 auf dein System-Codeset konvertiert werden. Und genau das sind die mehr als 2000 von dir beobachteten Aufrufe der Konvertierungsfunktion der codesets.library, von denen jeder einzelne Aufruf nach der Variablen ENV:codeset_default sucht. Weder YAM noch codesets.library können hier irgendetwas bemerken, verbessern oder abbrechen, weil die Arbeit - das Konvertieren von UTF8 nach ISO8859-x -  einfach getan werden muss und auch erfolgreich getan wird.

**Comment by halle-saale** [comment]
Okay. Danke dir. Dann werde ich die Einstellung für den System-Codeset und das Schreiben von Mails nach deinem Vorschlag übernehmen.
